require("jontheburger.theme")
require("jontheburger.opt")
require("jontheburger.lazy")
require("jontheburger.functions")
require("jontheburger.autocmd")
require("jontheburger.keymap")
require("jontheburger.syms")
