vim.api.nvim_set_keymap("i", "\\alpha", "α", { noremap = true })
vim.api.nvim_set_keymap("i", "\\beta", "β", { noremap = true })
vim.api.nvim_set_keymap("i", "\\gamma", "γ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\delta", "δ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\epsilon", "ε", { noremap = true })
vim.api.nvim_set_keymap("i", "\\zeta", "ζ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\eta", "η", { noremap = true })
vim.api.nvim_set_keymap("i", "\\theta", "θ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\iota", "ι", { noremap = true })
vim.api.nvim_set_keymap("i", "\\kappa", "κ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\lambda", "λ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\mu", "μ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\nu", "ν", { noremap = true })
vim.api.nvim_set_keymap("i", "\\xi", "ξ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\pi", "π", { noremap = true })
vim.api.nvim_set_keymap("i", "\\rho", "ρ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\sigma", "σ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\tau", "τ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\upsilon", "υ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\phi", "φ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\chi", "χ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\psi", "ψ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\omega", "ω", { noremap = true })

vim.api.nvim_set_keymap("i", "\\Gamma", "Γ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Delta", "Δ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Lambda", "Λ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Xi", "Ξ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Pi", "Π", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Sigma", "Σ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Upsilon", "ϒ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Phi", "Φ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Psi", "Ψ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Omega", "Ω", { noremap = true })

vim.api.nvim_set_keymap("i", "\\paragraph", "¶", { noremap = true })
vim.api.nvim_set_keymap("i", "\\section", "§", { noremap = true })

vim.api.nvim_set_keymap("i", "\\copyright", "©", { noremap = true })
vim.api.nvim_set_keymap("i", "\\registered", "®", { noremap = true })
vim.api.nvim_set_keymap("i", "\\tm", "™", { noremap = true })

vim.api.nvim_set_keymap("i", "\\cent", "¢", { noremap = true })
vim.api.nvim_set_keymap("i", "\\euro", "€", { noremap = true })
vim.api.nvim_set_keymap("i", "\\pound", "£", { noremap = true })
vim.api.nvim_set_keymap("i", "\\yen", "¥", { noremap = true })

vim.api.nvim_set_keymap("i", "\\esset", "ß", { noremap = true })
vim.api.nvim_set_keymap("i", "\\ae", "ä", { noremap = true })
vim.api.nvim_set_keymap("i", "\\oe", "ö", { noremap = true })
vim.api.nvim_set_keymap("i", "\\ue", "ü", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Ae", "Ä", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Oe", "Ö", { noremap = true })
vim.api.nvim_set_keymap("i", "\\Ue", "Ü", { noremap = true })

vim.api.nvim_set_keymap("i", "\\fun", "ƒ", { noremap = true })
vim.api.nvim_set_keymap("i", "\\cross", "×", { noremap = true })
vim.api.nvim_set_keymap("i", "\\dot", "•", { noremap = true })
vim.api.nvim_set_keymap("i", "\\deg", "°", { noremap = true })
vim.api.nvim_set_keymap("i", "\\nabla", "∇", { noremap = true })
vim.api.nvim_set_keymap("i", "\\partial", "∂", { noremap = true })

