require("config.opt")
require("config.lsp")
require("config.keymap")
require("config.lazy")
require("config.autocmd")
require("config.syms")
require("config.wiki")
require("config.vscode")
_G.F = require("config.fn")
