---@module "Main Entrypoint"
require("config.opt")
require("config.prefs")
require("config.lazy")
require("config.autocmd")
require("config.cmd")
require("config.ide")
require("config.keymap")
require("config.lsp")
require("config.syms")
require("config.wiki")
_G.F = require("config.fn")
