---@module "Language Server Protocol Config"
vim.lsp.enable("ansible")
vim.lsp.enable("armls")
vim.lsp.enable("bitbake")
vim.lsp.enable("clangd")
-- vim.lsp.enable("dts")
vim.lsp.enable("emmylua_ls")
vim.lsp.enable("harper")
vim.lsp.enable("json")
-- vim.lsp.enable("lua_ls")
vim.lsp.enable("md")
vim.lsp.enable("neocmakelsp")
vim.lsp.enable("nixd")
-- vim.lsp.enable("pyright")
-- vim.lsp.enable("pyrefly")
vim.lsp.enable("qml")
vim.lsp.enable("ruff")
vim.lsp.enable("sh")
vim.lsp.enable("slint")
-- vim.lsp.enable("sonarlint")
vim.lsp.enable("toml")
vim.lsp.enable("tsqueryls")
vim.lsp.enable("ty")
vim.lsp.enable("typescript")
vim.lsp.enable("vale")
vim.lsp.enable("yaml")
