---@module "Symbol Aliases"
vim.api.nvim_set_keymap("i", "\\alpha", "α", {})
vim.api.nvim_set_keymap("i", "\\beta", "β", {})
vim.api.nvim_set_keymap("i", "\\gamma", "γ", {})
vim.api.nvim_set_keymap("i", "\\delta", "δ", {})
vim.api.nvim_set_keymap("i", "\\epsilon", "ε", {})
vim.api.nvim_set_keymap("i", "\\zeta", "ζ", {})
vim.api.nvim_set_keymap("i", "\\eta", "η", {})
vim.api.nvim_set_keymap("i", "\\theta", "θ", {})
vim.api.nvim_set_keymap("i", "\\iota", "ι", {})
vim.api.nvim_set_keymap("i", "\\kappa", "κ", {})
vim.api.nvim_set_keymap("i", "\\lambda", "λ", {})
vim.api.nvim_set_keymap("i", "\\mu", "μ", {})
vim.api.nvim_set_keymap("i", "\\nu", "ν", {})
vim.api.nvim_set_keymap("i", "\\xi", "ξ", {})
vim.api.nvim_set_keymap("i", "\\pi", "π", {})
vim.api.nvim_set_keymap("i", "\\rho", "ρ", {})
vim.api.nvim_set_keymap("i", "\\sigma", "σ", {})
vim.api.nvim_set_keymap("i", "\\tau", "τ", {})
vim.api.nvim_set_keymap("i", "\\upsilon", "υ", {})
vim.api.nvim_set_keymap("i", "\\phi", "φ", {})
vim.api.nvim_set_keymap("i", "\\chi", "χ", {})
vim.api.nvim_set_keymap("i", "\\psi", "ψ", {})
vim.api.nvim_set_keymap("i", "\\omega", "ω", {})

vim.api.nvim_set_keymap("i", "\\micro", "µ", {})

vim.api.nvim_set_keymap("i", "\\Gamma", "Γ", {})
vim.api.nvim_set_keymap("i", "\\Delta", "Δ", {})
vim.api.nvim_set_keymap("i", "\\Lambda", "Λ", {})
vim.api.nvim_set_keymap("i", "\\Xi", "Ξ", {})
vim.api.nvim_set_keymap("i", "\\Pi", "Π", {})
vim.api.nvim_set_keymap("i", "\\Sigma", "Σ", {})
vim.api.nvim_set_keymap("i", "\\Upsilon", "ϒ", {})
vim.api.nvim_set_keymap("i", "\\Phi", "Φ", {})
vim.api.nvim_set_keymap("i", "\\Psi", "Ψ", {})
vim.api.nvim_set_keymap("i", "\\Omega", "Ω", {})

vim.api.nvim_set_keymap("i", "\\paragraph", "¶", {})
vim.api.nvim_set_keymap("i", "\\section", "§", {})
vim.api.nvim_set_keymap("i", "\\par", "¶", {})
vim.api.nvim_set_keymap("i", "\\sec", "§", {})

vim.api.nvim_set_keymap("i", "\\copyright", "©", {})
vim.api.nvim_set_keymap("i", "\\registered", "®", {})
vim.api.nvim_set_keymap("i", "\\tm", "™", {})

vim.api.nvim_set_keymap("i", "\\cent", "¢", {})
vim.api.nvim_set_keymap("i", "\\euro", "€", {})
vim.api.nvim_set_keymap("i", "\\pound", "£", {})
vim.api.nvim_set_keymap("i", "\\yen", "¥", {})

vim.api.nvim_set_keymap("i", "\\esset", "ß", {})
vim.api.nvim_set_keymap("i", "\\ss", "ß", {})
vim.api.nvim_set_keymap("i", "\\ae", "ä", {})
vim.api.nvim_set_keymap("i", "\\oe", "ö", {})
vim.api.nvim_set_keymap("i", "\\ue", "ü", {})
vim.api.nvim_set_keymap("i", "\\Ae", "Ä", {})
vim.api.nvim_set_keymap("i", "\\Oe", "Ö", {})
vim.api.nvim_set_keymap("i", "\\Ue", "Ü", {})

vim.api.nvim_set_keymap("i", "\\fun", "ƒ", {})
vim.api.nvim_set_keymap("i", "\\cross", "×", {})
vim.api.nvim_set_keymap("i", "\\dot", "•", {})
vim.api.nvim_set_keymap("i", "\\deg", "°", {})
vim.api.nvim_set_keymap("i", "\\nabla", "∇", {})
vim.api.nvim_set_keymap("i", "\\partial", "∂", {})
vim.api.nvim_set_keymap("i", "\\+=", "±", {})

vim.api.nvim_set_keymap("i", "\\_1", "₁", {})
vim.api.nvim_set_keymap("i", "\\_2", "₂", {})
vim.api.nvim_set_keymap("i", "\\_3", "₃", {})
vim.api.nvim_set_keymap("i", "\\_4", "₄", {})
vim.api.nvim_set_keymap("i", "\\_5", "₅", {})
vim.api.nvim_set_keymap("i", "\\_6", "₆", {})
vim.api.nvim_set_keymap("i", "\\_7", "₇", {})
vim.api.nvim_set_keymap("i", "\\_8", "₈", {})
vim.api.nvim_set_keymap("i", "\\_9", "₉", {})
vim.api.nvim_set_keymap("i", "\\^2", "²", {})
vim.api.nvim_set_keymap("i", "\\^3", "³", {})
vim.api.nvim_set_keymap("i", "\\^4", "⁴", {})
vim.api.nvim_set_keymap("i", "\\^5", "⁵", {})
vim.api.nvim_set_keymap("i", "\\^6", "⁶", {})
vim.api.nvim_set_keymap("i", "\\^7", "⁷", {})
vim.api.nvim_set_keymap("i", "\\^8", "⁸", {})
vim.api.nvim_set_keymap("i", "\\^9", "⁹", {})
vim.api.nvim_set_keymap("i", "\\half", "½", {})
vim.api.nvim_set_keymap("i", "\\third", "⅓", {})
vim.api.nvim_set_keymap("i", "\\quarter", "¼", {})

vim.api.nvim_set_keymap("i", "\\red", "🟥", {})
vim.api.nvim_set_keymap("i", "\\orange", "🟧", {})
vim.api.nvim_set_keymap("i", "\\yellow", "🟨", {})
vim.api.nvim_set_keymap("i", "\\green", "🟩", {})
vim.api.nvim_set_keymap("i", "\\blue", "🟦", {})
vim.api.nvim_set_keymap("i", "\\purple", "🟪", {})
vim.api.nvim_set_keymap("i", "\\brown", "🟫", {})
vim.api.nvim_set_keymap("i", "\\black", "⬛", {})
vim.api.nvim_set_keymap("i", "\\white", "⬜", {})

vim.api.nvim_set_keymap("i", "\\:)", "🙂", {})
vim.api.nvim_set_keymap("i", "\\smile", "🙂", {})
vim.api.nvim_set_keymap("i", "\\B)", "😎", {})
vim.api.nvim_set_keymap("i", "\\cool", "😎", {})

vim.keymap.set("i", "\\cr", function()
  local keys = vim.api.nvim_replace_termcodes("<C-v><CR>", true, false, true)
  vim.api.nvim_feedkeys(keys, "i", false)
end, { desc = "Insert literal ^M (CR)" })
